# Generated by Django 4.0.4 on 2022-04-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('breed', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('age', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
