# Generated by Django 4.0.4 on 2022-04-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('like new', 'like new'), ('used', 'used'), ('awful', 'awful')], default='new', max_length=10),
        ),
    ]
